### PR TITLE
Factor out `defaultSystems` (→ `systems`) & `allSystems` to flake input

### PR DESCRIPTION
**Pull request by bb010g**
This patch set allows for easy overriding of systems lists downstream via flake inputs, in a library-agnostic way. Ideally, all flakes that consume systems lists will avoid hard-coding them and instead consume them via flake inputs, allowing systems to be robustly introduced to or removed from evaluation. Flake inputs consisting of these pure, plain Nix source files should be the lowest-common denominator for systems list concerns.

Compatibility with existing direct access of `default.nix` is maintained. If that interface is not stable, then the introduction of `lib.nix` can be eliminated.

The `defaultSystems` input in flake-utils is the same as the `systems` input in <https://github.com/divnix/nosys>.

### CODE REVIEW

**Comment by bb010g** [comment]
Any thoughts / concerns about this concept and/or implementation?

**Review by zimbatm — COMMENTED** [review]
Thanks, it took me a minute to get it. It's an interesting idea. It introduces a new pattern:

Instead of exposing `allSystems` and `defaultSystems`, have a single overridable `systems` input. The `systems` key would become a new convention to all flakes; if exposed, it allows you to control the systems with which the flake will be built.

If you agree with this convention then let's deprecate `allSystems`. Users can use `nixpkgs.lib.platforms.all`. And map `defaultSystem` to the `systems` input. Having only one extra input also helps keep the lock files small.

**Comment by bb010g** [comment]
As long as changing `systems` doesn't cause unnecessary reevaluations, then I'm good with dropping the `defaultSystems` / `allSystems` divide. Cc/ @nrdxp since I stole this from them.

**Comment by bb010g** [comment]
I tried the `defaultSystems` → `systems` rename anyways, and it results in a few breaking changes.

**Comment by zimbatm** [comment]
Sorry, I meant only expose a single input called `systems`, and connect it to `defaultSystems.nix`. Ignore or deprecate `allSystems`. flake-utils is stable so we shouldn't break back-compat.

**Comment by bb010g** [comment]
What do you want to do about `eachDefaultSystem` and `eachDefaultSystemMap`? They can't directly rename to `eachSystem` and `eachSystemMap` because those names are taken by the parameterized variants.

**Comment by zimbatm** [comment]
I would keep all the library functions as is. allSystems is not overridable, but that's fine; I don't think people are really using it.

If it's unclear, push the previous version and I will do the changes.

**Comment by bb010g** [comment]
Alright, dropped all of the breaking renames (all but `defaultSystems` → `systems`) and kept backwards compatibility.

**Comment by bb010g** [comment]
Alright, reorganized and cleaned up using your ideas from <https://github.com/numtide/treefmt/pull/228> and <https://github.com/zimbatm/exp-flake-systems>.

**Comment by zimbatm** [comment]
thanks for your help! #93 introduces what I had in mind, I hope you won't mind me closing this PR

**Pull request closed without merging**
