### PR TITLE
eachSystem: push down `system` as far down as possible for Hydra jobs

### PR DESCRIPTION
**Pull request by Ma27**
Follow-up for #45, cc @zimbatm

### CODE REVIEW

**Comment by Ma27** [comment]
cc @zimbatm anything else missing to get this merged? :)

**Comment by Ma27** [comment]
ping @zimbatm :)

**Comment by Ma27** [comment]
@zimbatm anything missing to merge this? :)

**Comment by zimbatm** [comment]
Just being overloaded with notifications, sorry for the wait!

**Pull request merged**
