### PR TITLE
add aarch64-darwin as default system

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by blaggacao** [comment]
this seems to be causing problems downstream... But I see why it's here.

```
error: Package ‘ghc-8.10.4’ in /nix/store/slqryvgh7jw0jjsnr9zsjhyhmplh1ikx-source/pkgs/development/compilers/ghc/8.10.4.nix:263 is not supported on ‘aarch64-darwin’, refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

**Comment by zimbatm** [comment]
@Mic92 I have to revert this for now

**Comment by zimbatm** [comment]
reverted in acfb1951f051283fe3fed23045d09144e0ab5dd2

**Comment by Mic92** [comment]
The evaluation error is correct. Ghc does not build on aarch64 at the moment. @blaggacao if one of your packages depends on ghc than you need to mark at as broken on aarch64-darwin.

**Comment by Mic92** [comment]
I revert the revert here: https://github.com/numtide/flake-utils/pull/41

**Comment by blaggacao** [comment]
> @blaggacao if one of your packages depends on ghc than you need to mark at as broken on aarch64-darwin.

I'll check, but it IIRC I'd have to forward that advice to the `nixos` github org. Maybe upstream is not ready for this yet. But otoh, some nagging won't be bad either.

**Comment by zimbatm** [comment]
If the list of supported archs was exposed by nixpkgs, it would work better across branches.

**Pull request merged**
