### PR TITLE
Add convenient generic attribute

### PR DESCRIPTION
**Pull request by jD91mZM2**
Doing

```nix
{
  lib = {
    test = 1;
  };
} // eachDefaultSystem (system: {
  packages = { /* ... */ };
})
```

is really inconvenient. This lets you do

```nix
eachDefaultSystem (system: {
  lib.generic = {
    test = 1;
  };
  packages = { /* ... */ };
})
```

### CODE REVIEW

**Comment by zimbatm** [comment]
Agreed with the observation that the current situation could be better.

The proposed solution is not super discoverable and also re-instantiates the generic bits multiple times even if a single one will be used in the end.

What do you think of this instead?

```
eachDefaultSystem2 {
  generic = { lib.test = 1; };
  eachSystem = system: {
    packages = { /* ... */ };
  };
}
```

**Comment by jD91mZM2** [comment]
Good idea!

**Comment by zimbatm** [comment]
@jD91mZM2: pushed another proposal. I think that generic should just override the top-level.

**Comment by amitojsingh366** [comment]
https://www.redox-os.org/news/open-source-mental-health/

**Pull request closed without merging**
